//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.NoteManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TestWCFService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyNote", Namespace="http://schemas.datacontract.org/2004/07/TestWCFService")]
    [System.SerializableAttribute()]
    public partial class MyNote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TexteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modification {
            get {
                return this.ModificationField;
            }
            set {
                if ((this.ModificationField.Equals(value) != true)) {
                    this.ModificationField = value;
                    this.RaisePropertyChanged("Modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte {
            get {
                return this.TexteField;
            }
            set {
                if ((object.ReferenceEquals(this.TexteField, value) != true)) {
                    this.TexteField = value;
                    this.RaisePropertyChanged("Texte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoteManagerService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Client.NoteManagerService.CompositeType GetDataUsingDataContract(Client.NoteManagerService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Client.NoteManagerService.CompositeType> GetDataUsingDataContractAsync(Client.NoteManagerService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        int AddUser(string Pseudo, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string Pseudo, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connection", ReplyAction="http://tempuri.org/IService1/ConnectionResponse")]
        int Connection(string Pseudo, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connection", ReplyAction="http://tempuri.org/IService1/ConnectionResponse")]
        System.Threading.Tasks.Task<int> ConnectionAsync(string Pseudo, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Disconnection", ReplyAction="http://tempuri.org/IService1/DisconnectionResponse")]
        bool Disconnection(int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Disconnection", ReplyAction="http://tempuri.org/IService1/DisconnectionResponse")]
        System.Threading.Tasks.Task<bool> DisconnectionAsync(int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNote", ReplyAction="http://tempuri.org/IService1/AddNoteResponse")]
        int AddNote(string title, string note, int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNote", ReplyAction="http://tempuri.org/IService1/AddNoteResponse")]
        System.Threading.Tasks.Task<int> AddNoteAsync(string title, string note, int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificationNote", ReplyAction="http://tempuri.org/IService1/ModificationNoteResponse")]
        bool ModificationNote(int identification, string Titre, string Texte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificationNote", ReplyAction="http://tempuri.org/IService1/ModificationNoteResponse")]
        System.Threading.Tasks.Task<bool> ModificationNoteAsync(int identification, string Titre, string Texte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveNote", ReplyAction="http://tempuri.org/IService1/RemoveNoteResponse")]
        bool RemoveNote(int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveNote", ReplyAction="http://tempuri.org/IService1/RemoveNoteResponse")]
        System.Threading.Tasks.Task<bool> RemoveNoteAsync(int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Notes", ReplyAction="http://tempuri.org/IService1/NotesResponse")]
        Client.NoteManagerService.MyNote[] Notes(int identification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Notes", ReplyAction="http://tempuri.org/IService1/NotesResponse")]
        System.Threading.Tasks.Task<Client.NoteManagerService.MyNote[]> NotesAsync(int identification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.NoteManagerService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.NoteManagerService.IService1>, Client.NoteManagerService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Client.NoteManagerService.CompositeType GetDataUsingDataContract(Client.NoteManagerService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Client.NoteManagerService.CompositeType> GetDataUsingDataContractAsync(Client.NoteManagerService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int AddUser(string Pseudo, string Pass) {
            return base.Channel.AddUser(Pseudo, Pass);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string Pseudo, string Pass) {
            return base.Channel.AddUserAsync(Pseudo, Pass);
        }
        
        public int Connection(string Pseudo, string Pass) {
            return base.Channel.Connection(Pseudo, Pass);
        }
        
        public System.Threading.Tasks.Task<int> ConnectionAsync(string Pseudo, string Pass) {
            return base.Channel.ConnectionAsync(Pseudo, Pass);
        }
        
        public bool Disconnection(int identification) {
            return base.Channel.Disconnection(identification);
        }
        
        public System.Threading.Tasks.Task<bool> DisconnectionAsync(int identification) {
            return base.Channel.DisconnectionAsync(identification);
        }
        
        public int AddNote(string title, string note, int identification) {
            return base.Channel.AddNote(title, note, identification);
        }
        
        public System.Threading.Tasks.Task<int> AddNoteAsync(string title, string note, int identification) {
            return base.Channel.AddNoteAsync(title, note, identification);
        }
        
        public bool ModificationNote(int identification, string Titre, string Texte) {
            return base.Channel.ModificationNote(identification, Titre, Texte);
        }
        
        public System.Threading.Tasks.Task<bool> ModificationNoteAsync(int identification, string Titre, string Texte) {
            return base.Channel.ModificationNoteAsync(identification, Titre, Texte);
        }
        
        public bool RemoveNote(int identification) {
            return base.Channel.RemoveNote(identification);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveNoteAsync(int identification) {
            return base.Channel.RemoveNoteAsync(identification);
        }
        
        public Client.NoteManagerService.MyNote[] Notes(int identification) {
            return base.Channel.Notes(identification);
        }
        
        public System.Threading.Tasks.Task<Client.NoteManagerService.MyNote[]> NotesAsync(int identification) {
            return base.Channel.NotesAsync(identification);
        }
    }
}
